# Generated by Django 4.2 on 2023-04-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=2)),
                ('pulse', models.IntegerField()),
                ('respiration', models.IntegerField()),
                ('bp', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_registration.patientregistration')),
            ],
        ),
    ]
