# Generated by Django 4.2 on 2023-04-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPD_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
