# Generated by Django 4.2 on 2023-04-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='patient_info',
            new_name='opd_info',
        ),
    ]
